### ISSUE TITLE
Instructor feedback - project plan, scope, problem statement

### ISSUE THREAD

**Issue by pawaitemadisoncollege** [fiveSpeedMazdarati/PartyParrot#18]
WELL DONE! Particularly the happy cat gif.  Nice job with restful naming standards. Good to see that you are thinking about error conditions (404).

- [x] RE: the post and your question about using form params. I think that providing form params is a nice touch, you could do both form params and a regular URI as you have listed. 
- [x] I did not do a thorough code review, because I know there is lots in progress here, but remember to externalize any hard-coded values like urls to a properties file. 

You have a great start here - keep up the good work!

**Comment by fiveSpeedMazdarati** [comment]
Kelly did some serious research into how to get animated gif files into markdown.

**Comment by haandahl** [comment]
I stuck the url holding the JSON file in a properties file.  Do you all think anything else needs to go in there?

**Comment by haandahl** [comment]
None of us has come up with anything else for the properties file, so I am closing this issue.
