### ISSUE TITLE
local project structure

### ISSUE THREAD

**Issue by fiveSpeedMazdarati** [fiveSpeedMazdarati/PartyParrot#22]
I see that the properties are now split out (as they should be) - but what properties file did you create in the process? It isn't in the repository that I can see.

**Comment by haandahl** [comment]
aaaahhh... we have .properties in .gitignore.  I will make a quick branch to fix.

**Comment by haandahl** [comment]
Oops, accidentally just changed the master.  Anyway, it's there!
